#! /usr/bin/env bash

# check if the first arg is given.
if [ -z "$1" ]; then
    echo "No bucket name provided. Usage: ./create-bucket bucket-name"
    exit 1
fi 

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME --region us-west-2 --create-bucket-configuration LocationConstraint=us-west-2