#! /usr/bin/env bash

# check if the first arg is given.
if [ -z "$1" ]; then
    echo "No bucket name provided. Usage: ./create-bucket bucket-name"
    exit 1
fi 

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket $BUCKET_NAME --query Contents[].key | jq -n '{Objects: [inputs | .[] {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete_objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json